-- MySQL Script generated by MySQL Workbench
-- 09/14/17 17:26:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema todolist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todolist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todolist` DEFAULT CHARACTER SET utf8 ;
USE `todolist` ;

-- -----------------------------------------------------
-- Table `todolist`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolist`.`usuario` (
  `USR_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USR_NOME` VARCHAR(45) NOT NULL,
  `USR_EMAIL` VARCHAR(50) NOT NULL,
  `USR_SENHA` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`USR_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `todolist`.`tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolist`.`tarefa` (
  `TR_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TR_TITULO` VARCHAR(100) NOT NULL,
  `TR_DESCRICAO` VARCHAR(254) NOT NULL,
  `TR_STATUS` VARCHAR(1) NULL DEFAULT NULL,
  `USR_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`TR_ID`),
  INDEX `FK_USR_idx` (`USR_ID` ASC),
  CONSTRAINT `FK_USR`
    FOREIGN KEY (`USR_ID`)
    REFERENCES `todolist`.`usuario` (`USR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO usuario (USR_NOME,USR_EMAIL,USR_SENHA) VALUES ('admin','admin@admin.com','1234');
