-- MySQL Script generated by MySQL Workbench
-- 08/30/17 21:12:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TODOLIST
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TODOLIST
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TODOLIST` DEFAULT CHARACTER SET utf8 ;
USE `TODOLIST` ;

-- -----------------------------------------------------
-- Table `TODOLIST`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TODOLIST`.`USUARIO` (
  `USR_ID` INT NOT NULL AUTO_INCREMENT,
  `USR_NOME` VARCHAR(45) NOT NULL,
  `USR_EMAIL` VARCHAR(50) NOT NULL,
  `USR_SENHA` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`USR_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TODOLIST`.`TAREFA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TODOLIST`.`TAREFA` (
  `TR_ID` INT NOT NULL AUTO_INCREMENT,
  `TR_TITULO` VARCHAR(100) NOT NULL,
  `TR_DESCRICAO` VARCHAR(254) NOT NULL,
  `TR_STATUS` VARCHAR(1) NOT NULL,
  `USR_ID` INT NOT NULL,
  PRIMARY KEY (`TR_ID`),
  INDEX `FK_USR_idx` (`USR_ID` ASC),
  CONSTRAINT `FK_USR`
    FOREIGN KEY (`USR_ID`)
    REFERENCES `TODOLIST`.`USUARIO` (`USR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
